---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cert-manager
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: bigbang
spec:
  interval: 10m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: bigbang
spec:
  releaseName: cert-manager
  interval: 10m
  targetNamespace: cert-manager
  dependsOn: 
  - name: monitoring
    namespace: bigbang
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: bigbang
      version: 'v1.2.0'
  timeout: "5m"
  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
  