apiVersion: v1
kind: Secret
metadata:
    name: certmanager-secret-access-key
    namespace: cert-manager
data:
    key.json: ENC[AES256_GCM,data:weI3Ci+1qKGU1tLcVp3S39S8HOSFIqcDNG8YGrDJpCQ84skj6w/grywrSj/Kc4yKMYnaQpkE7AdgD71RE086VOdpH/4728EIfWfh1iUnediS9BXDw/T+TMlBsg==,iv:oE+nukT9Pyc+i3TXOcgZhXUmf58+lfJAcn73pV3LKnU=,tag:q40iFHd7iTi5Zis14QVC9A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:950698127059:key/739a21c8-6eaf-4bfe-a5dd-d5eac23d454d
          created_at: "2022-01-04T17:25:54Z"
          enc: AQICAHj9cqh7Ztas7PNrFWDZzzJ1ziyqfaJG6rdzOGqA5KFe5gEfuKZIrxmTF155rcXvuLgmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFWGlMZ6KJuVlNvPpAgEQgDtJntlHE6LMoiUa228+1M9JFjgdo1oJvz60r6Mo18LxQ1HzV1FbCBALLb/GyogsL0vbGELdAM8JwtUPHQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-04T17:25:55Z"
    mac: ENC[AES256_GCM,data:+RzAdA1rt+pNKP8SYwZxY7wrCpxyhhx4RGnKPNwphhK6CZzP1E4p6B8bjL/cxuFUilhBU0VtK2uuldDSrdMq/msHxEkgHTCyfsJRyseYgIHKw5G0PGAH0obX5Sy0kayT4kJ8tR90JhBQ7fgnYbKADMGWG+GSze+Iiauf3UjRyR0=,iv:Wyac53rCzmv33Ettxee+EfAw2pPsPGD1/ZJhkExuAUw=,tag:2315jLV6zN6wKzkwXKJ7Mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
