apiVersion: v1
kind: Secret
metadata:
    name: certmanager-secret-access-key
    namespace: cert-manager
data:
    key.json: ENC[AES256_GCM,data:SNaHG3SVhC4iJeD88hLbpojR3E3sAul2IZpeh5vrnotBuIDmW5Bz7iM90CAZq62I8zILI9+ROwDqlZ7qzogoaK7RmzYY9OryI4GW5Dx4v1/ChZ9ZJVrCljVcLw==,iv:yAltd/ntMhWN/bBq64foMPg+YeSZuEgEPaEbdPg1I3U=,tag:thh2FhfZZlc4jdPoMQOkWg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:950698127059:key/739a21c8-6eaf-4bfe-a5dd-d5eac23d454d
          created_at: "2022-01-04T13:55:08Z"
          enc: AQICAHj9cqh7Ztas7PNrFWDZzzJ1ziyqfaJG6rdzOGqA5KFe5gG8tReGgEtjIwnL5EMyq7MUAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5/8r9x4x4NplLBDyAgEQgDtWx1T4rms1+nY7p5KMw5ZfuP/hiZSdKGOqa+vLt0LlJFJxvfU7r2wHmRL1YFg0fsFIABbdZn19If3xxg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-02T23:08:57Z"
    mac: ENC[AES256_GCM,data:usGaFP+Ld+NyOlaDkcil/8WxMPEfmE8QFXggm0I4W/UMi9um6+7n6iBhzl+FXxkiTk6kXd+qQnaAoNb6DSzpWZSP8KjX8C7uk0UKYWTAqS6Asn6iQhmtgw81CYF0oUM8sOD4jAPTA5aOeWOs/ihWo7cqnjhjVEMPstGcs/pT41w=,iv:RiIYmpWYw0RbHt6b/bSEFTjT/OtieOdxgg14TmN46/w=,tag:4G/vTdl+s0nQ6riX1ij7Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
