apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/podinfo.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: common
  dependsOn:
  - name: bigbang
    namespace: bigbang