---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: credentials-copy
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/runyontr/credentials-copy
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-credentials-copy
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: credentials-copy
  interval: 1m0s
  values:
        source:
          name: flux-system
          namespace: flux-system
        destination:
          name: github-creds
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ironbank-credentials-copy
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: credentials-copy
  interval: 1m0s
  values:
      source:
        namespace: flux-system