apiVersion: v1
kind: Namespace
metadata:
  name: rapidfort
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rapidfort
  namespace: rapidfort
spec:
  interval: 1m0s
  ref:
    branch: main
    commit: 76823f6000ab2470d407c8d6f1e1c80256efeaf8
  url: ssh://git@github.com/Valid-Eval/infra_a-basin_ve-helm-chart.git # ADD IN RAPIDFORT GIT REPO
  secretRef:
    name: github-creds
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rapidfort
  namespace: rapidfort
spec:
  chart:
    spec:
      chart: /
      sourceRef:
        kind: GitRepository
        name: rapidfort
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: common
  - kind: ConfigMap
    name: environment
  - kind: Secret
    name: environment-rapidfort
  dependsOn:
  - name: istio
    namespace: bigbang
  - name: bigbang
    namespace: bigbang