namespace: rapidfort

resources:
  - deploy.yaml
  - credentials-copy.yaml

configMapGenerator:
  - name: common
    behavior: create
    files:
      - values.yaml=values.yaml
  - name: environment
    behavior: create
    literals:
    - values.yaml=
  
# Flux combines secrets and configmaps in `valuesFrom`.  Kustomize
# cannot distinguish between them when applying suffixes.  Therefore,
# the secrets must have different names than the configmaps
# While capital letters or dashes could be used, '-rapidfort' was chosen
# to make the difference obvious at a glance
secretGenerator:
  - name: environment-rapidfort
    behavior: create
    literals:
    - values.yaml=